### ISSUE TITLE
Segment the Odyssey Treebank

### ISSUE THREAD

**Issue by monzug** [alpheios-project/treebank_data#1]
see also issue alpheios-project/components#537 
go to https://texts-test.alpheios.net/text/urn:cts:greekLit:tlg0012.tlg002.alpheios-text-grc1/passage/1.1-1.30 and double click on ἔννεπε. it takes for ever to load the morphological information. Click on Diagram, no diagram is generated. Sometimes I do also get the yellow message on top or the page freezes and I need to reload.
see screenshots
![empty-diagram](https://user-images.githubusercontent.com/41396793/60026635-e76e2a80-9669-11e9-8e8e-0606f080a98e.JPG)

![diagram-loading-for-ever](https://user-images.githubusercontent.com/41396793/60026641-ec32de80-9669-11e9-8468-d761de13c4b0.JPG)

**Comment by balmas** [comment]
ok I have broken the Odyssey and Iliad treebanks into separate files per book.

@monzug I did this manually so I think we have to double check the edges of the books. I.e. do a lookup on a word in the first and last sentence of each book and make sure the tree loads and the morphology is disambiguated. I'm sorry this is a little tedious :-(

**Comment by monzug** [comment]
I compare with Perseus. some of the missing lines are present in the diagram, some are not.
We are missing line 444 from book 1 which is displayed in the diagram:
βούλευε φρεσὶν ᾗσιν ὁδὸν τὴν πέφραδ᾽ Ἀθήνη.
book 2, line 434: παννυχίη μέν ῥ᾽ ἥ γε καὶ ἠῶ πεῖρε κέλευθον.
book 3, line 497: δύσετό τ᾽ ἠέλιος σκιόωντό τε πᾶσαι ἀγυιαί.
book 4, line 847: ἀμφίδυμοι: τῇ τόν γε μένον λοχόωντες Ἀχαιοί.
book 5, line 493: δυσπονέος καμάτοιο φίλα βλέφαρ᾽ ἀμφικαλύψας.
book 6, line 331: ἀντιθέῳ Ὀδυσῆι πάρος ἣν γαῖαν ἱκέσθαι.
book 7, line 347: πὰρ δὲ γυνὴ δέσποινα λέχος πόρσυνε καὶ εὐνήν.
book 8, line 586: γίγνεται, ὅς κεν ἑταῖρος ἐὼν πεπνυμένα εἰδῇ.
book 9, line 566: ἄσμενοι ἐκ θανάτοιο, φίλους ὀλέσαντες ἑταίρους.
book 10, line 574: ὀφθαλμοῖσιν ἴδοιτ᾽ ἢ ἔνθ᾽ ἢ ἔνθα κιόντα;
book 11: no missing lines.
book 12, line 453: αὖτις ἀριζήλως εἰρημένα μυθολογεύειν.
book 13: no missing lines.
book 14, line 533: πέτρῃ ὕπο γλαφυρῇ εὗδον, Βορέω ὑπ᾽ ἰωγῇ.
book 15, line 557: ἐσθλὸς ἐὼν ἐνίαυεν, ἀνάκτεσιν ἤπια εἰδώς,
book 16, line 481: κοίτου τε μνήσαντο καὶ ὕπνου δῶρον ἕλοντο.
book 17, line 606: τέρποντ᾽: ἤδη γὰρ καὶ ἐπήλυθε δείελον ἦμαρ.  (not in the diagram)
book 18, line 428: βάν ῥ᾽ ἴμεναι κείοντες ἑὰ πρὸς δώμαθ᾽ ἕκαστος.
book 19, line 604: ἡδὺν ἐπὶ βλεφάροισι βάλε γλαυκῶπις Ἀθήνη.
book 20, line 1: we are missing the diagram - got the following error (see screenshot below)
book 20, last line: missing the diagram with error: No sentence with id 2191286 found
I did try to lookup few other words in book 20 and they all come out with no diagram.
also, missing line 394: θησέμεναι: πρότεροι γὰρ ἀεικέα μηχανόωντο.
book 21, line 433: πὰρ θρόνον ἑστήκει κεκορυθμένος αἴθοπι χαλκῷ.
book 22, line 501: κλαυθμοῦ καὶ στοναχῆς, γίγνωσκε δ᾽ ἄρα φρεσὶ πάσας.
book 23, line 372: νυκτὶ κατακρύψασα θοῶς ἐξῆγε πόληος.





![error-homer](https://user-images.githubusercontent.com/41396793/63609549-4e925780-c5a5-11e9-9d45-1f3d26a9f2f6.JPG)

**Comment by monzug** [comment]
Happy to say that there are no problems with diagrams on the Iliad.

**Comment by balmas** [comment]
hmm. ok, will investigate the Odyssey. Thanks!

**Comment by balmas** [comment]
ah, the lines are there in the Odyssey, there was just a systemic problem of the last line of each book not being numbered. 

need to look at the book 20 treebank, probably my error on splitting the files.

**Comment by balmas** [comment]
yep book 20 was the wrong data. that is fixed now. the line numbers will be fixed with the next build.

**Comment by balmas** [comment]
ready for testing.

**Comment by monzug** [comment]
tested in  Alpheios Embedded Library 3.0.0.37
Alpheios Components 1.2.34 
I am still not getting the diagrams for book 20: message is No sentence with id 2191053 found

The last lines are all in now.
I had a performance problem scrolling in book 15 (looking for line 577 gave an error because I made a mistake so I had to scroll down): it goes super slow, line by line. tested in FF.

**Comment by balmas** [comment]
ok, will look at this. if it turns out to be too hard to get working right, I think we could restrict the input to not allow ranges for now.

**Comment by balmas** [comment]
my mistake on Book 20. I didn't deploy the updated file properly.

**Comment by balmas** [comment]
should be correct now.

**Comment by monzug** [comment]
yes, book 20 diagrams are in. tested in FF and chrome and mobile.
